site_name: Alphaus Documentation

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  features:
  - navigation.tabs

nav:
- 'General':
  - 'index.md'
  - 'getting-started.md'
- 'Blue API':
  - 'blueapi/overview.md'
  - 'blueapi/authentication.md'
  - 'blueapi/client-sdks.md'

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
