site_name: Alphaus Documentation
theme:
  name: material
  logo: assets/alphaus.png
  features:
  - navigation.tabs
nav:
- 'General':
  - 'index.md'
  - 'getting-started.md'
- 'Blue API':
  - 'blueapi/overview.md'
  - 'changing-the-colors.md'
  - 'adding-a-comment-system.md'
