site_name: Alphaus Documentation
theme:
  name: material
  logo: assets/alphaus.png
  features:
  - navigation.tabs
nav:
- 'index.md'
- 'getting-started.md'
- 'changing-the-colors.md'
- 'adding-a-comment-system.md'
