site_name: Alphaus Documentation
copyright: Copyright &copy; 2021-2022 Alphaus Cloud. All rights reserved.

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  features:
  - navigation.tabs
  - navigation.expand

nav:
- 'General':
  - 'index.md'
  - 'Identity & Access Management': 'iam.md'
  - 'Ripple 🡥': 'https://docs.alphaus.cloud/v/ripple-en/'
  - 'Wave 🡥': 'https://docs.alphaus.cloud/v/wave-eng/'
  - 'Knowledgebase 🡥': 'https://help.alphaus.cloud/en/'
  - 'Previous documentation 🡥': 'https://docs.alphaus.cloud/'
  - 'System status 🡥': 'https://status.alphaus.cloud/'
- 'Blue API':
  - 'blueapi/overview.md'
  - 'blueapi/authentication.md'
  - 'CLI: bluectl': 'blueapi/bluectl.md'
  - 'APIs':
    - 'blueapi/apis/org.md'
    - 'blueapi/apis/kvstore.md'
    - 'blueapi/apis/iam.md'
    - 'blueapi/apis/cost.md'
  - 'blueapi/client-sdks.md'

extra:
  alternate:
  - name: English
    link: /docs/
    lang: en
  - name: 日本語
    link: /docs-ja/
    lang: ja

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true 
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
