site_name: Alphaus Documentation
theme:
  name: material
  logo: assets/alphaus.png
  features:
  - navigation.tabs
nav:
- 'General':
  - 'index.md'
  - 'getting-started.md'
- 'Blue API':
  - 'blueapi/overview.md'
  - 'blueapi/getting-started.md'
